### ISSUE TITLE
Support for newer mocker-generator version?

### ISSUE THREAD

**Issue by Leandro-bezerra-silva** [danibram/mocker-api-tester#1]
Hi there,

Is there any plans to tweak this code and support later versions of mocker-generator? (latest 2.5.2)
I tried npm install mocker-generator latest version but it failed on line 46
var m = require('mocker-data-generator')()

Thank you

**Comment by danibram** [comment]
Yes, im sorry about that, i forgot to update it.
I just updated to version 2.5.2
Thanks for the issue!

**Comment by Leandro-bezerra-silva** [comment]
Hi danibram,

Thank you for the update, but after this commit it is returning me an error when calling this API.

// Caliing schemas
TypeError: require(...).default is not a function
    at /Users/leandrosilva/mocker-api-tester/index.js:70:51
    at Layer.handle [as handle_request] (/Users/leandrosilva/mocker-api-tester/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/leandrosilva/mocker-api-tester/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/leandrosilva/mocker-api-tester/node_modules/express/lib/router/route.js:112:3)

// Caliing schema
TypeError: require(...).default is not a function
    at /Users/leandrosilva/mocker-api-tester/index.js:51:45
    at Layer.handle [as handle_request] (/Users/leandrosilva/mocker-api-tester/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/leandrosilva/mocker-api-tester/node_modules/express/lib/router/route.js:137:13)

Thank you

**Comment by Leandro-bezerra-silva** [comment]
No worries, thank you for the quick update.
Also, I'd remove the console.log on line 73.

Cheers.

**Comment by danibram** [comment]
Okei, thank you! Done!
